/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import DAL.DBConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RAVEN
 */
public class Form_8 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    DBConnection a=new DBConnection();
    Connection conn= a.ConnectDb();
    public int ketqua = 0;
    public String msg = "";
    String hieuxe = "";
    String ghichu = "";
    int id =0;
    int soluongxesua = 0;
    int soluongVTPT= 0;
    int soluongTienCong = 0;
    double TLDongia = 0L;
    public Form_8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel6 = new javax.swing.JPanel();
        tp_slxe = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SoluongXe = new javax.swing.JTable();
        txt_SLXeSuaTrongNgay = new javax.swing.JTextField();
        SuaTC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_soluongVTPT = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        SLVTPT = new javax.swing.JTable();
        SuaTC1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_soluongTienCong = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TIenCong = new javax.swing.JTable();
        SuaTC2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_TLDGBan = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TLDonGiaBan = new javax.swing.JTable();
        SuaTC3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(242, 242, 242));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tp_slxe.setBackground(new java.awt.Color(176, 196, 222));
        tp_slxe.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tp_slxe.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tp_slxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tp_slxeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tp_slxeMousePressed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(990, 500));

        SoluongXe.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SoluongXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Lượng Xe Cho Phép Sửa Chữa"
            }
        ));
        SoluongXe.setRowHeight(30);
        SoluongXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoluongXeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(SoluongXe);

        txt_SLXeSuaTrongNgay.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_SLXeSuaTrongNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SLXeSuaTrongNgayActionPerformed(evt);
            }
        });

        SuaTC.setBackground(new java.awt.Color(255, 255, 255));
        SuaTC.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SuaTC.setText("Sửa");
        SuaTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaTCActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Nhập số lượng xe cho phép sửa trong ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(681, 681, 681))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SLXeSuaTrongNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SuaTC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SLXeSuaTrongNgay)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuaTC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_slxe.addTab("Số lượng Xe Sửa Trong Ngày", jPanel2);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Số lượng VTPT");

        txt_soluongVTPT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_soluongVTPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongVTPTActionPerformed(evt);
            }
        });

        SLVTPT.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SLVTPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Lượng VTPT"
            }
        ));
        SLVTPT.setRowHeight(30);
        SLVTPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SLVTPTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(SLVTPT);

        SuaTC1.setBackground(new java.awt.Color(255, 255, 255));
        SuaTC1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SuaTC1.setText("Sửa");
        SuaTC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaTC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_soluongVTPT, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SuaTC1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soluongVTPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuaTC1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tp_slxe.addTab("Số lượng VTPT", jPanel1);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Số lượng tiền công");

        txt_soluongTienCong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_soluongTienCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongTienCongActionPerformed(evt);
            }
        });

        TIenCong.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        TIenCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Lượng tiền công"
            }
        ));
        TIenCong.setRowHeight(30);
        TIenCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIenCongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TIenCong);

        SuaTC2.setBackground(new java.awt.Color(255, 255, 255));
        SuaTC2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SuaTC2.setText("Sửa");
        SuaTC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaTC2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_soluongTienCong, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SuaTC2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soluongTienCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(SuaTC2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tp_slxe.addTab("Số lượng tiền công", jPanel3);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Nhập tỉ lệ giá bán");

        txt_TLDGBan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_TLDGBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TLDGBanActionPerformed(evt);
            }
        });

        TLDonGiaBan.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        TLDonGiaBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tỉ lệ giá bán"
            }
        ));
        TLDonGiaBan.setRowHeight(30);
        TLDonGiaBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TLDonGiaBanMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TLDonGiaBan);

        SuaTC3.setBackground(new java.awt.Color(255, 255, 255));
        SuaTC3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SuaTC3.setText("Sửa");
        SuaTC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaTC3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txt_TLDGBan, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SuaTC3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TLDGBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(SuaTC3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tp_slxe.addTab("Tỉ lệ giá bán", jPanel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Thay đổi quy định");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tp_slxe, javax.swing.GroupLayout.PREFERRED_SIZE, 942, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_slxe, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tp_slxeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tp_slxeMousePressed
        // TODO add your handling code here:
        
        int tabIndex = tp_slxe.getSelectedIndex();
                System.out.println("index" + tabIndex);
        if (tabIndex == 0){
            loadSLXeSuaChua();
        }else if(tabIndex == 1){
            loadSLVTPT();
        }else if(tabIndex == 2){
            loadSLTienCong();
        }else{
            loadTLDonGia();
        }        
//        
//        loadSLXeSuaChua();
//        loadSLVTPT();
//        loadSLTienCong();
    }//GEN-LAST:event_tp_slxeMousePressed

    private void tp_slxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tp_slxeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tp_slxeMouseClicked

    private void SuaTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaTCActionPerformed
        check_soluongxesuatrongngay();
    }//GEN-LAST:event_SuaTCActionPerformed

    private void txt_SLXeSuaTrongNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SLXeSuaTrongNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SLXeSuaTrongNgayActionPerformed

    private void SoluongXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoluongXeMouseClicked
        // TODO add your handling code here:
        //        soluongxesua = (int) SoluongXe.getValueAt(SoluongXe.getSelectedRow(), 0);
        //        System.out.println("soluong" + soluongxesua);
    }//GEN-LAST:event_SoluongXeMouseClicked

    private void txt_soluongVTPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongVTPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soluongVTPTActionPerformed

    private void SLVTPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLVTPTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SLVTPTMouseClicked

    private void SuaTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaTC1ActionPerformed
        // TODO add your handling code here:
        check_soluongVTPT();
    }//GEN-LAST:event_SuaTC1ActionPerformed

    private void txt_soluongTienCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongTienCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soluongTienCongActionPerformed

    private void TIenCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIenCongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TIenCongMouseClicked

    private void SuaTC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaTC2ActionPerformed
        // TODO add your handling code here:
        check_soluongTienCong();
    }//GEN-LAST:event_SuaTC2ActionPerformed

    private void txt_TLDGBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TLDGBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TLDGBanActionPerformed

    private void TLDonGiaBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TLDonGiaBanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TLDonGiaBanMouseClicked

    private void SuaTC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaTC3ActionPerformed
        // TODO add your handling code here:
        check_TiLeDonGiaBan();
    }//GEN-LAST:event_SuaTC3ActionPerformed

    public void check_soluongxesuatrongngay () {
        DefaultTableModel tbl_mod = (DefaultTableModel) SoluongXe.getModel();
        tbl_mod.setRowCount(0);
        int row_count = 0;
        try {
            Statement st = conn.createStatement();
            CallableStatement cs = conn.prepareCall("{call P_Check_SoLuongXeSuaTrongNgay(?, ?, ?)}");
            cs.setInt(1, Integer.valueOf(txt_SLXeSuaTrongNgay.getText()));
            ResultSet rs = cs.executeQuery();
            ketqua = cs.getInt(2);
            msg = cs.getString(3);
            if(ketqua == 0){
               JOptionPane.showMessageDialog(this, msg);
               txt_SLXeSuaTrongNgay.setText("");
               loadSLXeSuaChua();
               return;
            }else{
                JOptionPane.showMessageDialog(this, msg);
                loadSLXeSuaChua();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void check_soluongVTPT() {
        DefaultTableModel tbl_mod = (DefaultTableModel) SLVTPT.getModel();
        tbl_mod.setRowCount(0);
        int row_count = 0;
        try {
            Statement st = conn.createStatement();
            CallableStatement cs = conn.prepareCall("{call P_Check_SoLuongVTPT(?, ?, ?)}");
            cs.setInt(1, Integer.valueOf(txt_soluongVTPT.getText()));
            ResultSet rs = cs.executeQuery();
            ketqua = cs.getInt(2);
            msg = cs.getString(3);
            if(ketqua == 0){
               JOptionPane.showMessageDialog(this, msg);
               txt_soluongVTPT.setText("");
               loadSLVTPT();
               return;
            }else{
                JOptionPane.showMessageDialog(this, msg);
                loadSLVTPT();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void check_soluongTienCong() {
        DefaultTableModel tbl_mod = (DefaultTableModel) TIenCong.getModel();
        tbl_mod.setRowCount(0);
        int row_count = 0;
        try {
            Statement st = conn.createStatement();
            CallableStatement cs = conn.prepareCall("{call P_Check_SoLuongTienCong(?, ?, ?)}");
            cs.setInt(1, Integer.valueOf(txt_soluongTienCong.getText()));
            ResultSet rs = cs.executeQuery();
            ketqua = cs.getInt(2);
            msg = cs.getString(3);
            if(ketqua == 0){
               JOptionPane.showMessageDialog(this, msg);
               txt_soluongTienCong.setText("");
               loadSLTienCong();
               return;
            }else{
                JOptionPane.showMessageDialog(this, msg);
                loadSLTienCong();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    public void change_brandcar () {
//        DefaultTableModel tbl_mod = (DefaultTableModel) hieu_xe.getModel();
//        tbl_mod.setRowCount(0);
//        int row_count = 0;
//        try {
//            Statement st = conn.createStatement();
//            CallableStatement cs = conn.prepareCall("{call P_Change_BrandCar(?, ?, ?,?)}");
//            System.out.println("hieuxe:" + hieuxe);
//            cs.setString(1, hieuxe);
//            cs.setString(2, txt_GhiChu.getText());
//            cs.setInt(3, id);
//            cs.registerOutParameter(4, java.sql.Types.INTEGER);
//            cs.registerOutParameter(5, java.sql.Types.VARCHAR);
//            ResultSet rs = cs.executeQuery();
//            ketqua = cs.getInt(4);
//            msg = cs.getString(5);
//            if(ketqua == 0){
//               JOptionPane.showMessageDialog(this, msg);
//               txt_SLXeSuaTrongNgay.setText("");
//               //loadHieuXe();
//               return;
//            }else{
//                JOptionPane.showMessageDialog(this, msg);
//                //loadHieuXe();
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
     public void check_TiLeDonGiaBan() {
        DefaultTableModel tbl_mod = (DefaultTableModel) TLDonGiaBan.getModel();
        tbl_mod.setRowCount(0);
        int row_count = 0;
        try {
            Statement st = conn.createStatement();
            CallableStatement cs = conn.prepareCall("{call P_CheckTiLeDonGia(?, ?, ?)}");
            cs.setDouble(1, Double.valueOf(txt_TLDGBan.getText()));
            ResultSet rs = cs.executeQuery();
            ketqua = cs.getInt(2);
            msg = cs.getString(3);
            if(ketqua == 0){
               JOptionPane.showMessageDialog(this, msg);
               txt_TLDGBan.setText("");
               loadTLDonGia();
               return;
            }else{
                JOptionPane.showMessageDialog(this, msg);
                loadTLDonGia();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadSLXeSuaChua() {
        DefaultTableModel tbl_mod = (DefaultTableModel) SoluongXe.getModel();
        tbl_mod.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from v_soluongxesuachua");
            while(rs.next()){
                String tbData[]=
                        {
                            rs.getString(2)
                        };
                tbl_mod.addRow(tbData);
             }
            System.out.println("count " + tbl_mod.getRowCount());
            soluongxesua = (int) SoluongXe.getValueAt(SoluongXe.getSelectedRow(), 0);
            System.out.println("soluong" + soluongxesua);
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadSLVTPT() {
        DefaultTableModel tbl_mod = (DefaultTableModel) SLVTPT.getModel();
        tbl_mod.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from v_soluongvtpt");
            while(rs.next()){
                String tbData[]=
                        {
                            rs.getString(2)
                        };
                tbl_mod.addRow(tbData);
             }
            System.out.println("count " + tbl_mod.getRowCount());
            soluongVTPT = (int) SLVTPT.getValueAt(SLVTPT.getSelectedRow(), 0);
            System.out.println("soluongVTPT" + soluongVTPT);
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadSLTienCong() {
        DefaultTableModel tbl_mod = (DefaultTableModel) TIenCong.getModel();
        tbl_mod.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from v_soluongtiencong");
            while(rs.next()){
                String tbData[]=
                        {
                            rs.getString(2)
                        };
                tbl_mod.addRow(tbData);
             }
            System.out.println("count " + tbl_mod.getRowCount());
            soluongTienCong = (int) TIenCong.getValueAt(TIenCong.getSelectedRow(), 0);
            System.out.println("soluong" + soluongTienCong);
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadTLDonGia() {
        DefaultTableModel tbl_mod = (DefaultTableModel) TLDonGiaBan.getModel();
        tbl_mod.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from v_tiledongia");
            while(rs.next()){
                String tbData[]=
                        {
                            rs.getString(2)
                        };
                tbl_mod.addRow(tbData);
             }
            System.out.println("count " + tbl_mod.getRowCount());
            TLDongia = (double) TLDonGiaBan.getValueAt(TLDonGiaBan.getSelectedRow(), 0);
            System.out.println("TLDongia" + TLDongia);
        } catch (SQLException ex) {
            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    public void loadHieuXe() {
//        DefaultTableModel tbl_mod = (DefaultTableModel) hieu_xe.getModel();
//        tbl_mod.setRowCount(0);
//        int row_count = 0;
//        try {
//            Statement st = conn.createStatement();
//            ResultSet rs = st.executeQuery("select * from v_hieuxe");
//            while(rs.next()){
//                String tbData[]=
//                        {
//                            rs.getString(1),
//                            rs.getString(2),
//                            rs.getString(3)
//                        };
//                tbl_mod.addRow(tbData);
//             }
//            System.out.println("count " + tbl_mod.getRowCount());
//        } catch (SQLException ex) {
//            Logger.getLogger(Form_1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    public int getSL(){
        return soluongxesua;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SLVTPT;
    private javax.swing.JTable SoluongXe;
    private javax.swing.JButton SuaTC;
    private javax.swing.JButton SuaTC1;
    private javax.swing.JButton SuaTC2;
    private javax.swing.JButton SuaTC3;
    private javax.swing.JTable TIenCong;
    private javax.swing.JTable TLDonGiaBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane tp_slxe;
    private javax.swing.JTextField txt_SLXeSuaTrongNgay;
    private javax.swing.JTextField txt_TLDGBan;
    private javax.swing.JTextField txt_soluongTienCong;
    private javax.swing.JTextField txt_soluongVTPT;
    // End of variables declaration//GEN-END:variables
}
