/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DTO.TiepNhan;
import DTO.PhuTung;
import DTO.UserLoginDTO;
import java.util.Date;
import java.time.Instant;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import controller.ControllerImp;
import java.sql.Connection;
import java.sql.ResultSet;
import DAL.DBConnection;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
public class VehicleMaintenanceGUI extends javax.swing.JFrame {

    /*
    18/04
    Do du lieu vao bang từ sql
    */
    DBConnection a=new DBConnection();
    Connection conn= a.ConnectDb();
    DefaultTableModel model =new DefaultTableModel();
    //long impTotalMoney = 0L;
    public VehicleMaintenanceGUI (){
        initComponents();
        JTable  table = new JTable();
        //JScrollPane scrollPane = new JScrollPane(table);
        //getContentPane().add(scrollPane);
        tableTN=table;
        loadData();
    
    }
    
public void loadData () {
        try {
            int number;
            Vector<String> row, column = new Vector<>();
            row = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from view_xe");

            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();// trả về số cột

            for (int i = 1; i <= number; i++) {
                column.add(metadata.getColumnName(i)); // lay ra tieu de cua cac cot
            }
            model.setColumnIdentifiers(column);

            // Xóa bảng trước khi thêm dữ liệu
            model.setRowCount(0);

            while (rs.next()) {
                row = new Vector();
                for (int i = 1; i <= number; i++) {
                    row.addElement(rs.getString(i));
                }
                model.addRow(row);
            }
            
            
            tableTN.setModel(model);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    

    
   private ArrayList<TiepNhan> listTN;
   
    //vị trí
    /**
     * Creates new form VehicleMaintenanceGUI
     */
   
    UserLoginDTO dtoUserLogin = null;
    
    public VehicleMaintenanceGUI(UserLoginDTO user) {
        initComponents();
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        listTN=new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tableTN.getModel();
        this.setVisible(true);
        dtoUserLogin = user;
        this.setSize(1000, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menuBar1 = new java.awt.MenuBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        Phieu = new javax.swing.JPanel();
        aa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenChuXe = new java.awt.TextField();
        txtBienSo = new java.awt.TextField();
        txtHieuXe = new java.awt.TextField();
        txtDiaChi = new java.awt.TextField();
        txtSDT = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTN = new javax.swing.JTable();
        txtThem = new javax.swing.JButton();
        txtXoa = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        textUpdate = new javax.swing.JButton();
        txtNgayTiepNhan = new com.toedter.calendar.JDateChooser();
        btTim = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jPanel2.setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        panel1.setBackground(new java.awt.Color(159, 182, 205));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phiếu tiếp nhận xe");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        Phieu.setBackground(new java.awt.Color(130, 130, 130));
        Phieu.setMinimumSize(new java.awt.Dimension(1000, 480));
        Phieu.setPreferredSize(new java.awt.Dimension(950, 580));
        Phieu.setRequestFocusEnabled(false);

        aa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 255, 255));
        aa.setText("Tên chủ xe:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hiệu xe:");

        tb.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(255, 255, 255));
        tb.setText("Biển số:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa chỉ:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Số điên thoại:");

        txtTenChuXe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTenChuXe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTenChuXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenChuXeActionPerformed(evt);
            }
        });

        txtBienSo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBienSo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBienSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBienSoActionPerformed(evt);
            }
        });

        txtHieuXe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtHieuXe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtHieuXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHieuXeActionPerformed(evt);
            }
        });

        txtDiaChi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDiaChi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtSDT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtSDT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ngày tiếp nhận:");

        tableTN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên chủ xe", "Biển số", "Hiệu xe", "Địa chỉ", "SĐT", "Ngày tiếp nhận"
            }
        ));
        tableTN.setRowHeight(40);
        tableTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTN);

        txtThem.setBackground(new java.awt.Color(159, 182, 205));
        txtThem.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtThem.setText("Thêm");
        txtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemActionPerformed(evt);
            }
        });

        txtXoa.setBackground(new java.awt.Color(159, 182, 205));
        txtXoa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtXoa.setText("Xóa");
        txtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXoaActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtTim.setText("Tìm kiếm");
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        textUpdate.setBackground(new java.awt.Color(159, 182, 205));
        textUpdate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        textUpdate.setText("Sửa");
        textUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUpdateActionPerformed(evt);
            }
        });

        txtNgayTiepNhan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        btTim.setBackground(new java.awt.Color(159, 182, 205));
        btTim.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_car_search.png"))); // NOI18N
        btTim.setText("Tìm kiếm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PhieuLayout = new javax.swing.GroupLayout(Phieu);
        Phieu.setLayout(PhieuLayout);
        PhieuLayout.setHorizontalGroup(
            PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PhieuLayout.createSequentialGroup()
                            .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aa)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenChuXe, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(txtHieuXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(PhieuLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PhieuLayout.createSequentialGroup()
                        .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PhieuLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tb)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhieuLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTiepNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(txtBienSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PhieuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(textUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addComponent(jScrollPane1)
        );
        PhieuLayout.setVerticalGroup(
            PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenChuXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb)
                    .addComponent(txtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHieuXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PhieuLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayTiepNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Phieu, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Phieu, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jMenu2.setText("Home");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out-option.png"))); // NOI18N
        jMenu4.setText("Exit");
        jMenu4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUpdateActionPerformed
     try {   
        if (txtNgayTiepNhan.getDate() == null || txtTenChuXe.getText().isEmpty() || txtHieuXe.getText().isEmpty() ||
            txtDiaChi.getText().isEmpty() || txtSDT.getText().isEmpty() || txtBienSo.getText().isEmpty()) {
            System.err.println("One or more input fields are empty or null.");
            return;
        }

        
        java.util.Date utilStartDate = txtNgayTiepNhan.getDate();
        System.out.println("Ngày được chọn: " + utilStartDate);
        java.sql.Date date = new java.sql.Date(utilStartDate.getTime());
        PreparedStatement statement = conn.prepareStatement("{call P_CapNhap_Xe(?, ?, ?, ?, ?, ?)}");
        statement.setString(1, txtTenChuXe.getText());
        statement.setString(2, txtHieuXe.getText());
        statement.setString(3, txtDiaChi.getText());
        statement.setString(4, txtSDT.getText());
        statement.setDate(5, date);
        statement.setString(6, txtBienSo.getText());

        statement.executeUpdate();
        System.out.println("Procedure executed successfully.");
        loadData();

    } catch (SQLException e) {
        System.err.println("Error executing procedure: " + e.getMessage());
    }
    }//GEN-LAST:event_textUpdateActionPerformed

    private void txtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXoaActionPerformed
        // TODO add your handling code here:
       /*
        05/02
        */ // TODO add your handling code here:
        java.util.Date utilStartDate = txtNgayTiepNhan.getDate();
        java.sql.Date date = new java.sql.Date(utilStartDate.getTime());

        try {
            if (conn == null) {
                System.err.println("Connection is null. Make sure to establish a database connection.");
                return;
            }

            CallableStatement statement = conn.prepareCall("{call P_Xoa_Xe(?)}");
            statement.setString(1, txtBienSo.getText());

            statement.executeUpdate();

            JOptionPane.showMessageDialog(this, "Xóa Thành Công!");
            model.setRowCount(0);
            loadData();

        } catch (SQLException e) {
            System.err.println("Error executing procedure: " + e.getMessage());
    }
       
    }//GEN-LAST:event_txtXoaActionPerformed

    private void txtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemActionPerformed
       if (txtSDT.getText().equals("")) {
        txtSDT.setText("0");
    }
       java.util.Date utilStartDate = txtNgayTiepNhan.getDate();
            java.sql.Date sql_date = new java.sql.Date(utilStartDate.getTime());
//    java.util.Date utilDate = txtNgayTiepNhan.getDate();
//    java.sql.Date sql_date = new java.sql.Date(utilDate.getTime());
    try {
        CallableStatement cs = conn.prepareCall("{call P_Them_Xe(?, ?, ?, ?, ?, ?)}");

        cs.setString(1, txtBienSo.getText());
        cs.setString(2, txtTenChuXe.getText());
        cs.setString(3, txtHieuXe.getText());
        cs.setString(4, txtDiaChi.getText());
        cs.setInt(5, Integer.parseInt(txtSDT.getText()));
        cs.setDate(6, sql_date);

        cs.execute();

        JOptionPane.showMessageDialog(this, "Them Thanh Cong!");
        model.setRowCount(0);
        loadData(); // Reset the table data
        System.out.println("Kiem Tra load da tai them");

    } catch (SQLException ex) {
        if (ex.getSQLState().equals("45000")) {
            JOptionPane.showMessageDialog(this, "Record already exists.");
        } else {
            ex.printStackTrace();}}
      
        
    }//GEN-LAST:event_txtThemActionPerformed



    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed

    }//GEN-LAST:event_txtSDTActionPerformed

    
    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        TiepNhan p=new TiepNhan();
        int dc= p.getDiaChi().length();
        if(dc<=-1||dc>400)
            throw new ArithmeticException("Địa chỉ không hợp lệ");
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtHieuXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHieuXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHieuXeActionPerformed

    private void txtBienSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBienSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBienSoActionPerformed

    private void txtTenChuXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenChuXeActionPerformed

    }//GEN-LAST:event_txtTenChuXeActionPerformed

    private void tableTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTNMouseClicked
    boolean a=tableTN.isEditing();
        if (a==false){
            //JOptionPane.showMessageDialog(null, " ");
        }

        DefaultTableModel RecordTable = (DefaultTableModel) tableTN.getModel();
        int SelectRows = tableTN.getSelectedRow();
        for(int i = 0; i < tableTN.getSelectedRow();i++ ){
        txtBienSo.setText(RecordTable.getValueAt(SelectRows, 0).toString());
        txtDiaChi.setText(RecordTable.getValueAt(SelectRows, 5).toString());
        txtTenChuXe.setText(RecordTable.getValueAt(SelectRows, 3).toString());
        txtSDT.setText(RecordTable.getValueAt(SelectRows, 6).toString());
        txtHieuXe.setText(RecordTable.getValueAt(SelectRows, 4).toString());
        txtNgayTiepNhan.setDateFormatString(RecordTable.getValueAt(SelectRows, 7).toString());
        }
    }//GEN-LAST:event_tableTNMouseClicked

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        if(!dtoUserLogin.equals(null)){
            HomeGUI home = new HomeGUI(dtoUserLogin);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
       try {
          String bienSo = txtTim.getText(); 
        // Check if the input field is filled
        if (txtTim.getText().isEmpty()) {
            System.err.println("BienSo field is empty.");
            return;
        }

        // Create a connection
        try {
            // Prepare the stored procedure call
            String sql = "{CALL P_TimKiem(?)}";
            CallableStatement stmt = conn.prepareCall(sql);

            // Set the input parameter value
            stmt.setString(1, bienSo);

            // Execute the stored procedure
            ResultSet rs = stmt.executeQuery();

            // Process the returned result
            if (rs.next()) {
                
                // Check if the record exists
                if (rs.getString("Result").equals("Record not found.")) {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy bản ghi.", "Kết quả tìm kiếm", JOptionPane.WARNING_MESSAGE);
                } else {
                    // Display the found record information
                    String bienSoFound = rs.getString("BienSo"); 
                    String tenChuXe = rs.getString("TenChuXe");
                    String hieuXe = rs.getString("HieuXe");
                    String diaChi = rs.getString("DiaChi");
                    int dienThoai = rs.getInt("DienThoai");
                    Date ngayTiepNhan = rs.getDate("NgayTiepNhan");
                    
                    txtBienSo.setText(bienSo);
                    txtTenChuXe.setText(tenChuXe);
                    txtHieuXe.setText(hieuXe);
                    txtDiaChi.setText(diaChi);
                    txtSDT.setText(Integer.toString(dienThoai));
                    txtNgayTiepNhan.setDate(ngayTiepNhan);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy bản ghi.", "Kết quả tìm kiếm", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } catch (Exception e) {
        System.err.println("Error executing procedure: " + e.getMessage());
    }
    }//GEN-LAST:event_btTimActionPerformed

   public class PhieuNhapView extends javax.swing.JFrame
    {
        private ArrayList<TiepNhan> list;
        DefaultTableModel model;
        public PhieuNhapView()
        {
            initComponents();
            this.setLocationRelativeTo(null);
            list=new ArrayList<>();
            model=(DefaultTableModel)tableTN.getModel();
        }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleMaintenanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleMaintenanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(VehicleMaintenanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleMaintenanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        //</editor-fold>
//
//        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                //new PhieuNhapView().setVisible(true);
                }
           });
        }
        
 public class Control extends javax.swing.JFrame implements View{
     
    private List<TiepNhan> listTN;
    private DefaultTableModel modelTN;
    private DefaultTableModel modelPT;
    private List<PhuTung> listPT;
    private ControllerImp controller;

     public Control() {
        initComponents();
        this.setLocationRelativeTo(null);
        listTN = new ArrayList<>();
        modelTN = (DefaultTableModel) tableTN.getModel();
        controller = new ControllerImp();
        showTN();
    }
    
    public void addTN(TiepNhan TN) {
        listTN.add(TN);
        this.showData(listTN, modelTN);
        controller.writeToFile(listTN, "TUYEN.TXT");
    }
    
    public <T> void showData(List<T> list, DefaultTableModel modelTN) {
        modelTN.setRowCount(0);
        for (T t : list) {
            if (t instanceof TiepNhan) {
                TiepNhan p = (TiepNhan) t;
                modelTN.addRow(new Object[]{
                    p.getTenChuXe(), p.getBienSo(), p.getHieuXe(), p.getDiaChi(),  p.getSDT(), p.getNgayTiepNhan()
                });
            
        }
    }    
    }
        
    private void showTN() {
        listTN = controller.readDataFromFile("LX.TXT");
        if (listTN.size() > 0) {
            int mId = listTN.get(listTN.size() - 1).getstt();
            TiepNhan.setstt(mId + 1);
        }
        this.showData(listTN, modelTN);
    }
 
 
 }
        
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Phieu;
    private javax.swing.JLabel aa;
    private javax.swing.JButton btTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    private javax.swing.JTable tableTN;
    private javax.swing.JLabel tb;
    private javax.swing.JButton textUpdate;
    private java.awt.TextField txtBienSo;
    private java.awt.TextField txtDiaChi;
    private java.awt.TextField txtHieuXe;
    private com.toedter.calendar.JDateChooser txtNgayTiepNhan;
    private java.awt.TextField txtSDT;
    private java.awt.TextField txtTenChuXe;
    private javax.swing.JButton txtThem;
    private javax.swing.JTextField txtTim;
    private javax.swing.JButton txtXoa;
    // End of variables declaration//GEN-END:variables
}
